on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - dev

name: "Publish preview.closeread.dev"
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # for accessing this repo's assets in the container
      - name: Check out the repo
        uses: actions/checkout@v3
      # run the container, attaching this repo as a working directory
      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        env:
           NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        with:
          image: stat20/stat20-docker:latest
          options: -v ${{ github.workspace }}:/home/rstudio/closeread -e NETLIFY_AUTH_TOKEN=${{ secrets.NETLIFY_AUTH_TOKEN }}
          shell: bash
          run: |
            # exit if any command returns non-zero exit
            set -e

            cd /home/rstudio/closeread/
            
            # render and publish site
            quarto publish netlify docs --id ba6ca24d-1c6b-44b3-b907-16a2bfe5f4b5
